name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Roda o pipeline quando houver um push na branch main

jobs:
  build-and-push:
    name: Build e Push da Imagem Docker
    runs-on: ubuntu-latest
    # needs: test  # Só roda se os testes passarem

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

          # Passo 2: Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Versão do Node.js

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          npm install

      - name: Build Angular app
        run: |
          npm run build -- --prod

      - name: "Entrando no Dockerhub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Preparando Docker Build"
        uses: docker/setup-buildx-action@v3

      - name: "Gerando imagem do projeto"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            robsonarcoleze/safe-banking-app:${{ github.sha }}

      - name: "Saindo do Dockerhub"
        run: docker logout


