name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Roda o pipeline quando houver um push na branch main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Instalar dependências e rodar testes
        run: |
          mvn clean install
          mvn test

  build-and-push:
    name: Build e Push da Imagem Docker
    runs-on: ubuntu-latest
    needs: test  # Só roda se os testes passarem

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: "Entrando no Dockerhub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Preparando Docker Build"
        uses: docker/setup-buildx-action@v3

      - name: "Gerando imagem do projeto"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            robsonarcoleze/safe-banking-api:latest
            robsonarcoleze/safe-banking-api:${{ github.sha }}

      - name: "Saindo do Dockerhub"
        run: docker logout


